# main menu navigation
menu:
  Home: /
  Archive: /archives

widgets:
  - tag
  - archive
  - recent_posts
  - category
  - profile

# social config
social:
  zhihu:
  twitter: /
  facebook: /
  instagram: /
  github: NeoNexusX

user:
  name: NeoNexus
  avatar: https://s2.loli.net/2024/09/29/3wrsfjJK91xTciR.png
  location: Earth
  description: YOU CAN REDO
  footnotes: # footnotes

# documents: https://valine.js.org/quickstart.html
comment_valine:
  enable: true
  appId: hUPsiqArOXp6TNWbIGsRugoz-gzGzoHsz
  appKey: bMOEIPDsFffDM5KYhZcZFDwr


# dark
# light
# user-can-set
appearance: auto # Default value is auto

# Miscellaneous
favicon: images/favicon.ico

friend_links:
  - title: Google
    link: https://www.google.com/
  - title: Github
    link: https://www.github.com/
  - title: Bionet
    link: https://bionet.xmu.edu.cn/
# Google Analytics
ga_track_id:
ga_domain:

# Baidu Analytics
ba_track_id:

# picture of about page
about_pic: about.png

image_zoom:
  enable: true

mathjax:
  enable: true
  cdn: https://cdn.jsdelivr.net/npm/mathjax@2.7.8/MathJax.js?config=TeX-AMS-MML_HTMLorMML

